[build]
  publish = "."

[[redirects]]
  from = "/espana"
  to = "/espana.html"
  status = 200

[[redirects]]
  from = "/alemania"
  to = "/alemania.html"
  status = 200

[[redirects]]
  from = "/canada"
  to = "/canada.html"
  status = 200

[[redirects]]
  from = "/inglaterra"
  to = "/inglaterra.html"
  status = 200

[[redirects]]
  from = "/perfil"
  to = "/perfil.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
